language: node_js
node_js:
  - iojs-v1
  - iojs-v2
  - '0.12'
  - '0.11'
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: mAM4CJYCGvpiFmV2S5CSsMTnc7Tn0sI1ZpWv7jH+k4lpalDGpvGCg0lYusyGL4GCvj3Fi1Q7kaNVH4OrONmfnhQYwMZkUs5tVrA1sEeUgl8xmaA6JzDAAiwis6kkg1HilAdAhefVerY7u9rRZzEfUfFzJ9Oc4iVxG5BMRDeUmFgCb5bpPWDtlTY4g5KVg7CDwPyIGCjuSI872GF+hPn80XMuIinthQ3aCwwuBIfcxRRBsu2gAy+PYFPfv/p15BaZzTAXZh6rUUc0X9liwpAsj4p8/ixwGjs9yDQZq2yciE561o7SJuHjv9sLdWhedgM3FBUVR4XiHL6zV3JwNAXFMiYqbQ7B3ZkrKdpqs+xRnB1NW+DPRlGWdZ0Y1MxldMViSZBpTXk8NjaEEqvU2ANDPCzcINf4iihCTZtdNsI2OxKH+8/SmIj4QYMb3XJAzQeWo078xQfeO3wRFGhTsD2gMo0moNohOcGrUZJYwCN43RgMDq4meLlpr/SVMlqmS4qRIB8KuXekv4J7j8v5pkel3biORRO8Cs09Vra5q1uz5MGj9SS0aN06Qk9Q4Z3MmtRmlNn+VDYpIPWHmAp2p5hteiLhgnNSFYDN+rzw2hH5zqa00LeD1Hd8sHssfB9Y8t7wYbNj93v8yFebkPZrwkn7I/74w4mum0Ot8RcQXPyfaD4=
