language: node_js
node_js:
- '0.12'
- '0.11'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: ACC1nn4o2ZkCYvJcVqo8P/zA0kpq0q4Tkm+xjQk66VvnVquCsGiDtKJ/wHuLPw4/vf2Nnxtonu3KriUNuTbpoavwKx9pkQnETAlKMpGuAO4OgY9Qnf9Hr+j6L7Skyucou68UHwRX4PMF1V+2vi750UMx50SPRcUZPHELpg8az1yfIec1l1M8YSef14EMW5NAkgIZecJCy1mSeeyLP3UktRkDfpLiN0Fzao3NlTn045khA1n+/BcCmE7JBOEqqLFVrUWvoz5SNOaGWzuxKmbrn3mXuJ7COtk/Y/PGEagij9AavoVt8rPh5FCfAnbuJFwenDcT0oxh0zZjVNcNL3I2YmGmVAcKZ82f10HG84A63alckMBBCq2dtl120btkIrojPpohOlWly8rzDAOfSJIR9FQHFgOV14Y8hKawK3Uh+climRRCAKLhgCghGLeI5jWBOtOwT3sXNLBX3SPMg3dOf+CSYidrrXwfyj8aAZJsk/UtXq8zrL71HOgtKqW8PDphZjYq4nOPpgXbcFV8zQe3sYPbZ04k6XLOfGOswbBthP7IpwcoUDTi/9iGIuGGZmeqf1W9a52PpcOCnyxgw3BGgdjKTypQ2Dnz4zpOVxG3SiD5D/sMucNobeRv6oIMvdFNcV3Q1u7D8v+J8SjRN+hw8EdSA+ww95l5PvhY4wuFDQM=
  on:
    branch: master
    repo: FreeAllMedia/generator-oss-component
