language: node_js
node_js:
  - iojs-v1
  - iojs-v2
  - '0.12'
  - '0.11'
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: RlC2cbIrC64eRIy2xRHRpllyP483rg2BBzw3/6y0U+Dc4GQpKcz4R1Y9gPiAKXfzwIhuXvhnNGduX2hWa/mAxzKUtIEsEIb646JGv4dNoNDmGHTt20PcSGrlB8895mfr0IUSxx8lFzxK72gQjNflCqOeMWSgnyF9mTUVSH9lDyoCG0ZT1uPpupM6zbjwykRJCXVjJeUcstk6U2Gq2L8T6+2WOaclwM2drLnosNnQ8n/VOFrcL8kfc2RHslhBIcNvMJlImxV4KhYl7Jbn7T0s16GdCVyztiVlHVrGZQfNubWMF/Kfdd05XLPR551Q2rRHO1YnrWt9tXl6atrpGnWLV0Zq+ZrRd32Nqa8obl6DdIrD9E5KtDWww7e6HHXdVOQQr0sXybMjSbwkKowrnZ75ZaUrAhKXodjRspKiElCraYzjxPeEOLk1thZPQQtnP5QnMTRHSrXfomuYkxxLk03itAkaB8t4YR1qGAYo+Z9mQHGLPQ2bm0K13DMT/l0GfqIF1XluRFImnJwgDFHklBw3FjCU88TZV34zdGfZ478Evqkl8DLoynYD5uEjQ9kbJxNlAEPZno+aXRbsotFXMAxO7XCDsssnWsx8Nql79P/N3RvGhUN+HNrJwn71yhoHb/l0xbwAUw/VvQQ+2gWyYesjtdoO6qN6Kfs6R4qphXn8W9I=
