"use strict";

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

var _path = require("path");

var _path2 = _interopRequireDefault(_path);

var _yeomanGenerator = require("yeoman-generator");

var _os = require("os");

var _os2 = _interopRequireDefault(_os);

describe("oss-component generator", function () {
  var name = undefined;

  before(function (done) {
    name = "testComponent";
    _yeomanGenerator.test.run(_path2["default"].join(__dirname, "../../generators/app")).inDir(_path2["default"].join(_os2["default"].tmpdir(), "/temp-test")).withOptions({ "skip-install": true }).withPrompts({
      name: name,
      description: "some description",
      organizationName: "org",
      floobits: true,
      sauceLabs: true,
      travis: true,
      floobitsWorkspace: "someworkspace",
      repositoryUrl: "somerepo",
      issueTrackerUrl: "someissue",
      homepage: "somehomepage"
    }).on("end", done);
  });

  describe("(licensing)", function () {
    it("should create a LICENSE file", function () {
      _yeomanGenerator.assert.file(["LICENSE.md"]);
    });
  });

  describe("(documentation)", function () {
    it("should create a README file", function () {
      _yeomanGenerator.assert.file(["README.md"]);
    });
  });

  describe("(package-description)", function () {
    it("should create a package.json file", function () {
      _yeomanGenerator.assert.file(["package.json"]);
    });
  });

  describe("(code quality)", function () {
    it("should create files for code climate support", function () {
      _yeomanGenerator.assert.file([".codeclimate.yml"]);
      //autogenerated `lcov.info`
    });

    describe("(linting)", function () {
      it("should generate an eslint file", function () {
        _yeomanGenerator.assert.file([".eslintrc"]);
      });

      it("should generate an jshint file", function () {
        _yeomanGenerator.assert.file([".jshintrc"]);
      });
    });
  });

  describe("(collaboration support)", function () {
    describe("(coding)", function () {
      it("should create files for floobits support", function () {
        _yeomanGenerator.assert.file([".floo", ".flooignore"]);
      });
    });

    describe("(source code management)", function () {
      it("should create utiliy git files", function () {
        _yeomanGenerator.assert.file([".gitignore"]);
      });
    });
  });

  describe("(testing)", function () {
    it("should create files for karma", function () {
      _yeomanGenerator.assert.file([".karma.conf.js"]);
    });

    it("should create files for sauce labs", function () {
      _yeomanGenerator.assert.file([".sauce.json"]);
    });
  });

  describe("(continuous integration)", function () {
    it("should create files for Travis CI", function () {
      _yeomanGenerator.assert.file([".travis.yml"]);
    });
  });

  describe("(automation)", function () {
    it("should create gulp related files", function () {
      _yeomanGenerator.assert.file(["gulpfile.babel.js", "tasks/build.js", "tasks/build-lib.js", "tasks/build-spec.js", "tasks/test.js", "tasks/test-local.js", "tasks/test-browsers.js", "paths.json"]);
    });
  });

  describe("(functionality)", function () {
    it("should generate an index", function () {
      _yeomanGenerator.assert.file(["index.js"]);
    });

    it("should generate a mock entry point with his test", function () {
      _yeomanGenerator.assert.file(["es6/lib/" + name + ".js", "es6/spec/" + name + ".spec.js"]);
    });

    //suspended due to the time that takes to install dependencies
    //tested also with the actual yo command
    xit("should create es5 compatible files", function () {
      _yeomanGenerator.assert.file(["es5/lib/" + name + ".js", "es5/spec/" + name + ".spec.js"]);
    });
  });
});